### ISSUE TITLE
Feature request: Actions for Telescope picker

### ISSUE THREAD

**Issue by ansidev** [aaditeynair/conduct.nvim#1]
Example scenario:

1. Run `Telescope conduct projects` to open project list.
2. Put the cursor at a project name.
3. Press hotkey to apply action on the selected project.

Example:

| Mapping | Action         |
|---------|----------------|
| e       | rename project |
| d       | delete project |
| r       | reload project |

**Comment by aaditeynair** [comment]
This seems useful. However, do you think there will be a use case for the reload project hotkey? Isn't it more effecient to just run `ConductReloadProjectConfig`?

**Comment by aaditeynair** [comment]
I've added the delete and rename functions to both telescope projects and sessions. Thanks for the suggestion!
