### ISSUE TITLE
[Feature Request] API for checking if a directory is a project

### ISSUE THREAD

**Issue by Ciel-MC** [aaditeynair/conduct.nvim#3]
I'm trying to make my startup screen smart:
- If no directory is supplied, open conduct project picker
- If directory is supplied, open telescope search file

I want to open conduct session picker if the current directory has a conduct project instead of always find_file, but it looks like the current API doesn't provide that function, it would be nice to have that.

My idea for implementation is a method to return the entire project list as a list of projects(akin to current_project), which allows people to work from there, and eliminates the need for something like list_all_projects. Furthermore, the method could accept a list of strings as what field to query, so you can only query, for example, the `cwd` for performance reasons for whatever.

**Comment by aaditeynair** [comment]
Currently all project config files are stored in separate JSON files in the conduct folder. Returning all project data with the current implementation will require us to read all project files. I might have to change the way conduct stores project data. However, I can see this being useful, so I'll look into it.

**Comment by Ciel-MC** [comment]
That's great, thank you.

**Comment by Ciel-MC** [comment]
This came up again when I am doing my config today(oops), I wanted to map <leader>p to a session menu if I am in a project and project menu if I am not. Maybe you can, for the time being, add a function that just loads a project in as an object only(without loading them in), so the user has more operating space? Since then I would be able to get project list and get the object for each project, and operate from there.

**Comment by aaditeynair** [comment]
I believe this snippet does what you've described:
```lua
vim.keymap.set("n", "<leader>p", function()
    local conduct = require("conduct")
    if next(conduct.current_project) == nil then
        vim.cmd("Telescope conduct projects")
        return
    end

    vim.cmd("Telescope conduct sessions")
end)

```

**Comment by Ciel-MC** [comment]
> I believe this snippet does what you've described:
> 
> ```lua
> vim.keymap.set("n", "<leader>p", function()
>     local conduct = require("conduct")
>     if next(conduct.current_project) == nil then
>         vim.cmd("Telescope conduct projects")
>         return
>     end
> 
>     vim.cmd("Telescope conduct sessions")
> end)
> ```

Oh, does that work if I just launch into a project instead of entering via Conduct though?

PS: I personally prefer using require'telescope'.extension.conduct.session/project instead, always enjoyed pure lua over vim.cmd hacks.

**Comment by aaditeynair** [comment]
I'm not sure what you meant by launching into a project instead of entering via conduct. The line `next(conduct.current_project) == nil` checks if the `current_project` variable conduct provides is an empty table. If it is, it means that no project is loaded and it then launches the project search. If a project is loaded, it opens the sessions search.

**Comment by Ciel-MC** [comment]
I mean if I did `nvim path/to/project` instead of loading a project using Conduct

**Comment by aaditeynair** [comment]
No that wouldn't work. Conduct doesn't automatically load projects. As of the latest commit I just pushed, conduct provides a vim command and lua function to load the first project that has the cwd as the current dir. I haven't updated the docs yet. I have also created a function that returns the data of all projects, so you can use that as well. I should also probably mention that the sessions list will not work until you load a project.

**Comment by Ciel-MC** [comment]
Nice, what is the interface for getting all the data?

**Comment by aaditeynair** [comment]
`require("conduct").get_all_project_data()` returns the data of all the projects. You can use this to check if a project exists in the current directory. Or you can use `require("conduct").load_cwd_data()` to load the project automatically.

**Comment by aaditeynair** [comment]
Looking back at your first comment, this snippet should achieve what you're looking for:
```lua
local conduct = require("conduct")
local project = ""
local cwd = vim.fn.getcwd()

for _, project_data in ipairs(conduct.get_all_project_data()) do
    if project_data.cwd == cwd then
        project = project_data.name
        break
    end
end

if project ~= "" then
    conduct.load_project(project)
    vim.cmd("Telescope conduct sessions")
else
    vim.cmd("Telescope find_files")
end
```
